// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package ordersDataStore

import (
	"context"
)

type Querier interface {
	//CreateOrder
	//
	//  INSERT INTO orders (order_id, order_qty, amount)
	//  VALUES (?, ?, ?)
	CreateOrder(ctx context.Context, arg CreateOrderParams) error
	//GetAllOrders
	//
	//  SELECT order_id, order_qty, amount, created_at, updated_at
	//  FROM orders
	//  ORDER BY created_at DESC
	GetAllOrders(ctx context.Context) ([]*Order, error)
	//GetOrderByID
	//
	//  SELECT order_id, order_qty, amount, created_at, updated_at
	//  FROM orders
	//  WHERE order_id = ?
	GetOrderByID(ctx context.Context, orderID string) (*Order, error)
}

var _ Querier = (*Queries)(nil)
