// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package orderRoDataStore

import (
	"database/sql"
)

type Order struct {
	OrderID   string       `json:"order_id"`
	OrderQty  int32        `json:"order_qty"`
	Amount    string       `json:"amount"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}
